import { precacheAndRoute } from 'workbox-precaching';

// Precaching all assets generated by Vite
// self.__WB_MANIFEST is injected by the VitePWA plugin during build
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for push notifications
self.addEventListener('push', function(event) {
  console.log('[Service Worker] Push Received.', event.data ? event.data.text() : 'No data payload');

  let notificationData = {};
  
  try {
    if (event.data) {
      notificationData = event.data.json();
    }
  } catch (e) {
    // Fallback if not JSON
    notificationData = {
      title: 'TimeTracker Reminder',
      body: event.data ? event.data.text() : 'Have you checked in today?'
    };
  }

  const title = notificationData.title || 'Check-in Reminder';
  const options = {
    body: notificationData.body || 'Don\'t forget to log your daily check-in!',
    icon: '/TimeTrackerApp-V0.2/icons/adaptive-icon.png',
    badge: '/TimeTrackerApp-V0.2/icons/adaptive-icon.png',
    vibrate: [100, 50, 100],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: '2'
    },
    tag: 'checkin-reminder-' + Date.now(),
    requireInteraction: true,
    actions: [
      {
        action: 'open',
        title: 'Open App',
      },
      {
        action: 'close',
        title: 'Close',
      },
    ]
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// Handle notification interaction
self.addEventListener('notificationclick', function(event) {
  console.log('[Service Worker] Notification click Received.', event.action);

  event.notification.close();

  if (event.action !== 'close') {
    // Note: Assuming app is hosted under /TimeTrackerApp-V0.2/
    const targetUrl = '/TimeTrackerApp-V0.2/';

    event.waitUntil(
      clients.matchAll({ type: 'window', includeUncontrolled: true }).then(function(clientList) {
        // If there's an active window, focus it
        for (let i = 0; i < clientList.length; i++) {
          const client = clientList[i];
          if (client.url.includes('/TimeTrackerApp-V0.2/') && 'focus' in client) {
            return client.focus();
          }
        }
        // Otherwise open a new window
        if (clients.openWindow) {
          return clients.openWindow(targetUrl);
        }
      })
    );
  }
});
